part of 'sign_in_sign_up_bloc.dart';

@freezed
class SignInSignUpWithInitialState with _$SignInSignUpWithInitialState {
  const factory SignInSignUpWithInitialState({
    required String message,
    required OtpArgument otpArgument,
    required bool isLoading,
    required bool isFailure,
    required bool isPasswordObscure,
    required bool isVerifyButtonActive,
    required bool isSignUpButtonActive,
    required bool isSignInButtonActive,
    required bool isConfirmPasswordObscure,
    required TextEditingController emailEditingController,
    required TextEditingController passwordEditingController,
    required TextEditingController confirmPasswordEditingController,
    required FocusNode emailFocusNode,
    required FocusNode passwordFocusNode,
    required FocusNode confirmPasswordFocusNode,
    required bool isRefreshRequired,
    required SocialResponseModel? socialResponseModel,
    required bool isBoxChecked,
    required bool isPasswordCheckerHidden,
    required GlobalKey<FormState> formKey,
    required bool isAtLeastEightCharChecked,
    required bool isAtLeastOneLowerCaseChecked,
    required bool isAtLeastOneUpperCaseChecked,
    required bool isAtLeastOneDigitChecked,
    required bool isAtLeastOneSpecialCharChecked,
    required Authentication authenticationType,
    required String routeName,
  }) = _SignInSignUpWithInitialState;

  factory SignInSignUpWithInitialState.initial() => SignInSignUpWithInitialState(
    message: AppStrings.global_empty_string,
    isLoading: false,
    isFailure: false,
    isPasswordObscure: true,
    authenticationType: Authentication.signIn,
    isConfirmPasswordObscure: true,
      isVerifyButtonActive: false,
    isSignInButtonActive: false,
    otpArgument: const OtpArgument(),
    emailEditingController: TextEditingController(),
    passwordEditingController: TextEditingController(),
    confirmPasswordEditingController: TextEditingController(),
    emailFocusNode: FocusNode(),
    passwordFocusNode: FocusNode(),
    confirmPasswordFocusNode: FocusNode(),
    formKey: GlobalKey<FormState>(),
    socialResponseModel: null,
    isRefreshRequired: false,
    isBoxChecked: false,
    routeName: AppStrings.global_empty_string,
    isPasswordCheckerHidden: true,
    isAtLeastEightCharChecked: false,
    isAtLeastOneLowerCaseChecked: false,
    isAtLeastOneUpperCaseChecked: false,
    isAtLeastOneDigitChecked: false,
    isAtLeastOneSpecialCharChecked: false,
      isSignUpButtonActive: false,
  );
}
