// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6yZtNNWzNwv1ged1xqS-EEeeC83fVuEk',
    appId: '1:479833908908:android:484a09bdf3a3a5dd546109',
    messagingSenderId: '479833908908',
    projectId: 'rmn-events-e2b56',
    storageBucket: 'rmn-events-e2b56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3lT7VHTThngV7d4eLnASs6Ne3ogKPpDU',
    appId: '1:479833908908:ios:3f77517eb6cb9f17546109',
    messagingSenderId: '479833908908',
    projectId: 'rmn-events-e2b56',
    storageBucket: 'rmn-events-e2b56.firebasestorage.app',
    androidClientId: '479833908908-0fbgq44kcthj6t2maahe9mirsorvp1t9.apps.googleusercontent.com',
    iosClientId: '479833908908-vpn4hvijgt7bkqc57gnh6au2fsvrtooa.apps.googleusercontent.com',
    iosBundleId: 'com.rmnevents.dev',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPT7VSHRVl0WIrjLWPDqDUQPHkfzk2TU4',
    appId: '1:479833908908:web:1aa29becf3e250bf546109',
    messagingSenderId: '479833908908',
    projectId: 'rmn-events-e2b56',
    authDomain: 'rmn-events-e2b56.firebaseapp.com',
    storageBucket: 'rmn-events-e2b56.firebasestorage.app',
    measurementId: 'G-FBDHYMLLY1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3lT7VHTThngV7d4eLnASs6Ne3ogKPpDU',
    appId: '1:479833908908:ios:68a63556514f41b4546109',
    messagingSenderId: '479833908908',
    projectId: 'rmn-events-e2b56',
    storageBucket: 'rmn-events-e2b56.firebasestorage.app',
    androidClientId: '479833908908-0fbgq44kcthj6t2maahe9mirsorvp1t9.apps.googleusercontent.com',
    iosClientId: '479833908908-itf1c59daqgst8r7ftagb53lo411m3te.apps.googleusercontent.com',
    iosBundleId: 'com.rmnevents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPT7VSHRVl0WIrjLWPDqDUQPHkfzk2TU4',
    appId: '1:479833908908:web:50cf52d1fcbf9784546109',
    messagingSenderId: '479833908908',
    projectId: 'rmn-events-e2b56',
    authDomain: 'rmn-events-e2b56.firebaseapp.com',
    storageBucket: 'rmn-events-e2b56.firebasestorage.app',
    measurementId: 'G-N2JL46G4CQ',
  );

}