on:
  push:
    branches:
      - development

name: RMN EVENTS - Development Android
jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    env:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEY_PATH: ${{ secrets.KEY_PATH}}
      KEY_PASS: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      STORE_PASS: ${{ secrets.KEYSTORE_PASSWORD }}
#      CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}

    steps:

      - uses: actions/checkout@v3


      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'


      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: any
      - run: flutter --version


      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV


      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - run: echo $KEYSTORE | base64 -di >  ${{secrets.KEY_PATH}}
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --release -t lib/main_dev.dart --flavor=dev  --split-per-abi


      - name: Upload APK Dev
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repository_name }} -- dev apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-dev-release.apk

